const fs = require('fs');

const analyses = [
    { "nom": "NUMERATION-FORMULE SANGUINE (NFS)" },
    { "nom": "SEROLOGIE HIV" },
    { "nom": "MAGNESIUM SANGUIN" },
    { "nom": "TAUX DE PROTHROMBINE" },
    { "nom": "IONOGRAMME URINAIRE" },
    { "nom": "BILIRUBINE DIRECT" },
    { "nom": "BILIRUBINE TOTALE" },
    { "nom": "C- REACTIVE PROTEINE (CRP)" },
    { "nom": "ACE (antigéne carcino-embryonnaire)" },
    { "nom": "CHOLESTEROL HDL" },
    { "nom": "CHOLESTEROL LDL" },
    { "nom": "CHOLESTEROL TOTAL" },
    { "nom": "SEROLOGIE DE L'HEPATITE B" },
    { "nom": "SEROLOGIE DE L'HEPATITE C" },
    { "nom": "V.D.R.L" },
    { "nom": "ANTISTREPTOLYSINE O (ASLO)" },
    { "nom": "PROGESTERONE" },
    { "nom": "PSA TOTALE" },
    { "nom": "PROTIDES TOTAUX" },
    { "nom": "PROTEINURIE DE 24 H" },
    { "nom": "TESTOSTERONE" },
    { "nom": "TSHus" },
    { "nom": "CPK (Créatine Phosphokinase):" },
    { "nom": "CREATININE URINAIRE" },
    { "nom": "OESTRADIOL E2" },
    { "nom": "FERRITINEMIE" },
    { "nom": "FT4 (Thyroxine libre)" },
    { "nom": "FT3 ( Tri-iodothyronine libre)" },
    { "nom": "MICRO ALBUMINURIE DES 24H" },
    { "nom": "Glycémie post-prandiale" },
    { "nom": "FSH" },
    { "nom": "GLYCEMIE A JEUN" },
    { "nom": "VITESSE DE SEDIMENTATION (V.S)" },
    { "nom": "LIPASE" },
    { "nom": "ACIDE URIQUE SANGUIN" },
    { "nom": "TEMPS DE CEPHALINE KAOLIN (T.C.K)" },
    { "nom": "Gamma Glutamyl Transférase" },
    { "nom": "ANTIGENE CA 19-9" },
    { "nom": "TOXOPLASMOSE IgM" },
    { "nom": "HbA1C (Hb glyquée)" },
    { "nom": "AMYLASURIE" },
    { "nom": "ALAT (GPT)" },
    { "nom": "ALBUMINEMIE" },
    { "nom": "IONOGRAMME SANGUIN" },
    { "nom": "FER SERIQUE" },
    { "nom": "LDH (Lactate Deshydrogenase):" },
    { "nom": "TRIGLYCERIDES" },
    { "nom": "FIBRINOGENE" },
    { "nom": "PHOSPHATASES ALCALINES" },
    { "nom": "OSMOLALITE URINAIRE" },
    { "nom": "OSM UREE" },
    { "nom": "OSM GLUCOSE" },
    { "nom": "- Ac Anti-CMV  IgG" },
    { "nom": "- Ac Anti-CMV  IgM" },
    { "nom": "- AC ANTI-HAV IGG" },
    { "nom": "- Ac anti-HBc TOTAUX" },
    { "nom": "- AC ANTI-HBC TOTAUX (IGG+IGM) CORE T" },
    { "nom": "- Antigéne HBe" },
    { "nom": "17-Hydroxyprogesterone" },
    { "nom": "A.C.T.H" },
    { "nom": "AC ANTI BP 180" },
    { "nom": "AC ANTI BP230" },
    { "nom": "AC ANTI CARDIOLIPINE IgG" },
    { "nom": "AC ANTI GP210" },
    { "nom": "Ac Anti HAV IgM" },
    { "nom": "AC ANTI IA2" },
    { "nom": "AC ANTI INSULINE" },
    { "nom": "AC ANTI MITOCHONDRIE" },
    { "nom": "AC ANTI SP100" },
    { "nom": "Ac anti peau" },
    { "nom": "AC ANTI-ACIDE GLUTAMIQUE DECARBOXYLASE" },
    { "nom": "AC ANTI-ANTIGENES ENA" },
    { "nom": "AC ANTI-CARDIOLIPINE IGM" },
    { "nom": "AC ANTI-CARDIOLIPINE Screen (IgG, IgM)" },
    { "nom": "Ac anti-gliadine" },
    { "nom": "Ac Anti-HCV" },
    { "nom": "AC ANTI-INSULINE" },
    { "nom": "AC ANTI-RECEPTEUR DE LA TSH" },
    { "nom": "AC ANTI-RETICULINE" },
    { "nom": "Ac anti-transglutaminase IgA" },
    { "nom": "Ac anti-transglutaminase IgG" },
    { "nom": "AC ANTICOLAGENE" },
    { "nom": "Ac AntiGliadine IgA" },
    { "nom": "Ac AntiGliadine IgG" },
    { "nom": "AC HBC" },
    { "nom": "AC-ANTI  ACETYLCHOLINE" },
    { "nom": "ACE (antigéne carcino-embryonnaire )" },
    { "nom": "ACIDE LACTIQUE" },
    { "nom": "acide methylmalonique urinaire" },
    { "nom": "ACIDE URIQUE URINAIRE" },
    { "nom": "ACIDE VALPOIQUE(DEPAKINE)" },
    { "nom": "ACIDE VANYL MANDELIQUE (V M A)" },
    { "nom": "AFP (alpha-foetoproteine)" },
    { "nom": "ALBUMINE DU LIQUIDE D'ASCITE" },
    { "nom": "Aldolase" },
    { "nom": "ALDOSTERONE" },
    { "nom": "ALDOSTERONE URINAIRE" },
    { "nom": "ALPHA 1 ANTI TRYPSINE" },
    { "nom": "amoniémie" },
    { "nom": "AMYLASE" },
    { "nom": "Amylase dans le Liquide Abdominal" },
    { "nom": "ANGIOTENSINE II" },
    { "nom": "ANTI ACTINE F" },
    { "nom": "Anti corps anti beta 2 glycoproteine IgG / IgM" },
    { "nom": "anti hepatite C total" },
    { "nom": "anti lupique circulant" },
    { "nom": "Anti muscle lisse" },
    { "nom": "ANTI-GAD" },
    { "nom": "ANTI-TPO(Anticorps Anti-thyroperoxidase)" },
    { "nom": "ANTICORPS ANTI -THYROGLOBILINE (anti TG)" },
    { "nom": "Anticorps anti DNA natif" },
    { "nom": "anticorps anti HBC IgM" },
    { "nom": "Anticorps anti HCV" },
    { "nom": "Anticorps anti phospholipides ( APL)" },
    { "nom": "Anticorps anti-cytoplasme des polynucléaires neutro philes (ANCA)" },
    { "nom": "Anticorps anti-endomysium IgA" },
    { "nom": "Anticorps Anti-HBe" },
    { "nom": "Anticorps Anti-HBs" },
    { "nom": "Anticorps anti-muscles lisses" },
    { "nom": "Anticorps anti-nucléaire ( AAN)" },
    { "nom": "Anticorps anti-peptide cycliques citrulline?s ( ACCP )" },
    { "nom": "Anticorps anti-saccharomyces cervisiae (ASCA)" },
    { "nom": "Anticorps Anti-Treponema Pallidum TPHA )" },
    { "nom": "ANTICORPS ANTICELLULES PARIéTALES" },
    { "nom": "ANTICORPS ANTIFACTEUR INTRINSéQUE" },
    { "nom": "ANTIGENE CA 125" },
    { "nom": "ANTIGENE CA 15-3" },
    { "nom": "Antigéne HBs" },
    { "nom": "ANTITHROMBINE 3" },
    { "nom": "ASAT(GOT)" },
    { "nom": "aspergillose" },
    { "nom": "AUTO-ANTICORPS ANTI-IA2" },
    { "nom": "AVIDITE DES IGG ANTI TOXOPLASMIQUE" },
    { "nom": "AVIDITE DES IgG ANTI-RUBEOLIQUE" },
    { "nom": "B2 microglobuline" },
    { "nom": "BETA- HCG" },
    { "nom": "Biochimie du liquide d'ascite" },
    { "nom": "C1 INIHIBITEUR ( Action fonctionnelle )" },
    { "nom": "C3" },
    { "nom": "C3 PRO ACTIVATEU" },
    { "nom": "C4" },
    { "nom": "CALCIUM SANGUIN" },
    { "nom": "CALCIUM URINAIRE" },
    { "nom": "Calciurie" },
    { "nom": "Calciurie des 24h" },
    { "nom": "CALPROTECTINE FECALE" },
    { "nom": "Calprotectine Fécale (CF)" },
    { "nom": "CAPACITE DE FIXATION DU FER (T.I.B.C)" },
    { "nom": "CARIOTYPE" },
    { "nom": "CERULEOPLASMINE" },
    { "nom": "CH 50(complement hémolythique totale)" },
    { "nom": "CH5" },
    { "nom": "CHAINE LEGERE SANGUINE" },
    { "nom": "chaine legere urinaire" },
    { "nom": "Chaine legere urinaire" },
    { "nom": "CHAINE LEGERE URINAIRE" },
    { "nom": "Chaines légéres Kappa" },
    { "nom": "Chaines légéres Lambda" },
    { "nom": "CHARGE VIRALE C (ARN VHC)" },
    { "nom": "CHARGE VIRALE HEPATITE B" },
    { "nom": "CHIMIE DES URINES" },
    { "nom": "CHLAMYDIA" },
    { "nom": "CHROMATOGRAPHI DES ACIDE AMINES" },
    { "nom": "CLAIRANCE DE LA CREATININE" },
    { "nom": "CLAIRANCE DE LA CREATININE - Cockcroft-Gault" },
    { "nom": "COEFFICIENT DE SATURATION" },
    { "nom": "COMPTE D'ADDIS- HAMBURGER(HLM)" },
    { "nom": "COOMBS INDIRECT" },
    { "nom": "COPRO-PARASITOLOGIE DES SELLES" },
    { "nom": "COPROCULTURE" },
    { "nom": "Cortisol" },
    { "nom": "Cortisol 15 mn" },
    { "nom": "CORTISOL URINAIRE" },
    { "nom": "CPK (Créatine Phosphokinase):" },
    { "nom": "CREATININE SANGUINE" },
    { "nom": "Créatinine" },
    { "nom": "CUIVRE ECHANGEABLE" },
    { "nom": "CUIVRE SANGUIN" },
    { "nom": "CUIVRE URINAIRE" },
    { "nom": "CUIVRE URINAIRE (CUPRIURIE)" },
    { "nom": "CYTOMEGALOVIRUS (CMV)  IgG" },
    { "nom": "CYTOMEGALOVIRUSE CMV IGM" },
    { "nom": "D-DIMERES" },
    { "nom": "DELTA 4 ANDROSTENDIONE" },
    { "nom": "DENSITE" },
    { "nom": "DEPAKINASE" },
    { "nom": "DEPISTAGE DU DIABETE GESTATIONNEL (HGPO)" },
    { "nom": "DERIVES METHOXYLES (Métanéphrines)" },
    { "nom": "DESMOGLEINE 1 ET 3" },
    { "nom": "DHEA-S (Déhydroépiandrostérone-sulfate )" },
    { "nom": "Diurése:" },
    { "nom": "DOSAGE DE L'HAPTOGLOBINE" },
    { "nom": "DOSAGE DE LA CARBAMAZIPINE(TEGRETOLEMIE)" },
    { "nom": "DOSAGE DE LA VITAMINE B 12" },
    { "nom": "DOSAGE DES DERIVES METHOXYLES" },
    { "nom": "DOSAGE DES IGA" },
    { "nom": "DOSAGE DES IgE TOTALES" },
    { "nom": "DOSAGE DES IGG" },
    { "nom": "DOSAGE DES IgG SERIQUES" },
    { "nom": "DOSAGE DES IGM" },
    { "nom": "DOSAGE DES IgM SERIQUES" },
    { "nom": "DéHYDROéPIANDROSTéRONE" },
    { "nom": "ECB de l'écoulement mammelonnaire" },
    { "nom": "ECB DE LA GOUTTE URETHRALE" },
    { "nom": "ECB DE LIQUIDE DE PONCTION" },
    { "nom": "ECB DE LIQUIDE SYNOVIAL" },
    { "nom": "ECB DES EXPECTORATIONS" },
    { "nom": "ECB des Gouttes Urétrales" },
    { "nom": "ECB DU PRELEVEMENT DE GORGE" },
    { "nom": "ECB DU PRELEVEMENT VAGINAL" },
    { "nom": "ECB DU PRELEVEMENT VAGINAL/PRELEVEMENT" },
    { "nom": "ECB SPERME ( MYCO / CHLAM )" },
    { "nom": "ECB VAGINAL ( MYCO /UREA )" },
    { "nom": "ELECTROPHORESE DES PROTEINES" },
    { "nom": "ELECTROPHORESES D'HEMOGLOBINE" },
    { "nom": "ELECTROPHORéSE DES PROTEINES URINAIRES" },
    { "nom": "Enzyme de conversion de l'angiotensine" },
    { "nom": "Examen Bactériologique des selles" },
    { "nom": "EXAMEN CYTO-BACTERIOLOGIQUE DE PUS" },
    { "nom": "EXAMEN CYTO-BACTERIOLOGIQUE DES URINES" },
    { "nom": "EXAMEN CYTOBACTéRIOLOGIQUE DE PUS" },
    { "nom": "EXAMEN D'UN FROTTIS DES SECRETIONS NASALES" },
    { "nom": "Examen Mycologique" },
    { "nom": "EXAMEN MYCOLOGIQUE" },
    { "nom": "EXAMEN PARASITOLOGIQUE DES SELLES" },
    { "nom": "FACTEUR  IX" },
    { "nom": "Facteur Anti-nucléaire (FAN)" },
    { "nom": "facteur de willebrand" },
    { "nom": "FACTEUR RHUMATOIDE" },
    { "nom": "Facteur V" },
    { "nom": "FACTEUR V" },
    { "nom": "FACTEUR VIII" },
    { "nom": "facteur willebrand" },
    { "nom": "Facteurs Rhumatoides IgM" },
    { "nom": "FIBROTEST ACTITEST" },
    { "nom": "FOLATES (vit B9)" },
    { "nom": "FRACTION C3 DU COMPLEMENT" },
    { "nom": "FRACTION C4  DU COMPLEMENT" },
    { "nom": "FROTTIS NASAL" },
    { "nom": "FROTTIS SANGUIN" },
    { "nom": "FROTTIS SANGUIN COLORé AU MGG" },
    { "nom": "FROTTIS SANGUIN:" },
    { "nom": "FRUCTOSAMINE" },
    { "nom": "FT3 ( Tri-iodothyronine libre )" },
    { "nom": "FT4 (Thyroxine libre )" },
    { "nom": "Gamma Glutamyl Transférase" },
    { "nom": "GH (Hormone de croissance)" },
    { "nom": "GLUCOSE" },
    { "nom": "GLUCOSE-6-PHOSPHATE DESHYDROGENASE (G6-PDH)" },
    { "nom": "GLUCOSURIE" },
    { "nom": "Glycémie post-prandiale" },
    { "nom": "GROUPAGE" },
    { "nom": "GROUPAGE PHENOTYPE" },
    { "nom": "HbA1C (Hb glyquée)" },
    { "nom": "HBs Antigene" },
    { "nom": "HCG, MARQUEUR TUMORAL" },
    { "nom": "Helicobacter Pylori IgG" },
    { "nom": "hepatite C igG" },
    { "nom": "hepatite C igM" },
    { "nom": "Herpes HSV 1/2 IgG" },
    { "nom": "Herpes HSV 1/2 IgM" },
    { "nom": "HERPES SIMPLEX VIRUS 1 ET 2" },
    { "nom": "HERPES SIMPLEX VIRUS G + M (CERBA)" },
    { "nom": "HLA B27" },
    { "nom": "HOMOCYSTEINE" },
    { "nom": "HOMOCYSTEINE URINAIRE" },
    { "nom": "HORMAONE ANTI MULLURIENNE" },
    { "nom": "HORMONE ANTI MULLERIENNE  (AMH)" },
    { "nom": "HORMONE ANTI-DIURETIQUE" },
    { "nom": "Hormone de croissance (GH)" },
    { "nom": "Hormone de croissance (GH)  +15 mn" },
    { "nom": "Hormone de croissance (GH)  +30 mn" },
    { "nom": "Hormone de croissance (GH)  +60 mn" },
    { "nom": "Hormone de croissance (GH)  00 mn" },
    { "nom": "Hormone de croissance (GH)  120 mn" },
    { "nom": "Hormone de croissance (GH)  90 mn" },
    { "nom": "Hormone de croissance (GH)  T120" },
    { "nom": "Human papillomavirus" },
    { "nom": "Hyper Glycémie Provoquée Per Os" },
    { "nom": "HYPERGLYCEMIE PROVOQUE PAR VOIE ORAL (HGPO) Grossesse" },
    { "nom": "HYPERGLYCEMIE PROVOQUEE PAR VOIE ORALE (HGPO) hors grossesse" },
    { "nom": "Hépatite B-détermination quantitative -charge virale (VHB)" },
    { "nom": "IgA anti-transglutaminase tissulaire" },
    { "nom": "IgA SERIQUES" },
    { "nom": "IgE Alimentaire ( TROPHATOP )" },
    { "nom": "IGE LAIT DE VACHE" },
    { "nom": "IgE specifique : panel pédiatrique)" },
    { "nom": "IGE SPECIFIQUES  ALIMENTAIRE" },
    { "nom": "IGE SPECIFIQUES (RESPIRATOIRE)" },
    { "nom": "IGE SPECIFIQUES DU BLE" },
    { "nom": "IgE Spécifique ( Lait de Vache)" },
    { "nom": "IgE spécifiques :Panel pédiatrique" },
    { "nom": "IgEspécifique respiratoire" },
    { "nom": "IGG 4" },
    { "nom": "IgG anti-transglutaminase" },
    { "nom": "IMMUNOTYPAGE" },
    { "nom": "Immunoélectrophorése des protéines sérique (IEP)" },
    { "nom": "Immunoélectrophorése des protéines urinaire (IEP)" },
    { "nom": "Inhibine B" },
    { "nom": "INSULINE" },
    { "nom": "IONOGRAMME  URINAIRE" },
    { "nom": "JAK2 MUTATION V617F" },
    { "nom": "LATEX" },
    { "nom": "LH" },
    { "nom": "LIPIDE TOTAUX" },
    { "nom": "liquide de ponction pleural" },
    { "nom": "LKM" },
    { "nom": "LKM1" },
    { "nom": "LOCUS B" },
    { "nom": "LYME (igg/igm)" },
    { "nom": "MAGNESIUM URINAIRE" },
    { "nom": "MEDULLOGRAMME" },
    { "nom": "MICRO  ALBUMINURIE DES 24H" },
    { "nom": "Microalbuminurie" },
    { "nom": "Microalbuminurie échantillon" },
    { "nom": "MYCOLOGIE" },
    { "nom": "MYCOPLASMA" },
    { "nom": "MYCOPLASMA PNEUMONIAE IGG" },
    { "nom": "MYCOPLASMA PNEUMONIAE IGM" },
    { "nom": "Mycoplasme sur sperm" },
    { "nom": "MYTOCHODRIE POSITIF TYPAGE M2" },
    { "nom": "NT PRO BNP- BRAIN NATRIURETIC PEPTIDE" },
    { "nom": "OXALURIE" },
    { "nom": "P. DE LA GOUTTE URETHRALE" },
    { "nom": "Parasitologie des selles" },
    { "nom": "PEPTIDE C" },
    { "nom": "PHOSPHORE SANGUIN" },
    { "nom": "PHOSPHORE URINAIRE" },
    { "nom": "Phénylalanine" },
    { "nom": "PIGMENT BILIAIRE" },
    { "nom": "Poumons eleveur d'oiseau" },
    { "nom": "PRELEVEMENT DE GORGE" },
    { "nom": "PROCALCITONINE" },
    { "nom": "PROLACTINE" },
    { "nom": "PROTEIN C" },
    { "nom": "PROTEIN S" },
    { "nom": "PROTEINE C ACTIVE" },
    { "nom": "PROTEINES DE BENCE- JONES" },
    { "nom": "Proteines de Bence-Jones" },
    { "nom": "proteinurie" },
    { "nom": "PSA LIBRE" },
    { "nom": "PTH" },
    { "nom": "QUANTIFERON" },
    { "nom": "RAI (panel )" },
    { "nom": "RAPPORT ALBUMINE / CREATININE URINAIRE" },
    { "nom": "RAPPORT ALDOSTERONE / RENINE" },
    { "nom": "RECHERCHE D'Ag D'HELICOBACTER PYLORI DANS LES SELLES" },
    { "nom": "RECHERCHE DE BK" },
    { "nom": "Recherche de Chlamydia sur sperme" },
    { "nom": "Recherche de Chlamydia sur un prélévement vaginal" },
    { "nom": "Recherche de Mycoplasme dans l'urétre" },
    { "nom": "Recherche de Mycoplasme dans les sécrétions vaginales:" },
    { "nom": "Recherche de mycoplasme sur prélévement de sperme:" },
    { "nom": "Recherche de sang dans les selles" },
    { "nom": "RECHERCHE DE SPERME DANS LES URINES" },
    { "nom": "recherge ag aspergillaire" },
    { "nom": "RENINE" },
    { "nom": "RT-PCR SARS COV-2" },
    { "nom": "RUBEOLE IgG" },
    { "nom": "RUBEOLE IgM" },
    { "nom": "SARS- COV-2 TYPE IGG" },
    { "nom": "SARS- COV-2 TYPE IGM" },
    { "nom": "SARS-COV-2 RNA SCREENING ( REAL TIME RT-PCR )" },
    { "nom": "SCOTCH TEST (RECHERCHE DE PARASITES INTESTINAUX)" },
    { "nom": "sels biliare" },
    { "nom": "SERO-AGGLUTINATION DE WRIGHT" },
    { "nom": "SEROLOGIE ASPERGILLOSE" },
    { "nom": "SEROLOGIE CHLAMYDIA IgA" },
    { "nom": "SEROLOGIE CHLAMYDIA IgG" },
    { "nom": "SEROLOGIE CHLAMYDIA IgM" },
    { "nom": "SEROLOGIE COVID IGG" },
    { "nom": "SEROLOGIE COVID IGM" },
    { "nom": "SEROLOGIE COVID-19" },
    { "nom": "SEROLOGIE DE L'HEPATITE A (IgM)" },
    { "nom": "SEROLOGIE DE LA BRUCELLOSE" },
    { "nom": "SEROLOGIE DE LA CYTOMEGALO VIRUS" },
    { "nom": "SEROLOGIE DE LA MALADIE COELIAQUE" },
    { "nom": "serologie de wright" },
    { "nom": "SEROLOGIE EBV" },
    { "nom": "SEROLOGIE HEPATITE  E" },
    { "nom": "SEROLOGIE HYDATIDOSE (Dépistage )" },
    { "nom": "SEROLOGIE HYDATIQUE" },
    { "nom": "SEROLOGIE LEISHMANIOSE" },
    { "nom": "serologie leptospirose" },
    { "nom": "SEROLOGIE MYCOPLASME" },
    { "nom": "SEROLOGIE SYPHILIS" },
    { "nom": "SEROLOGIE VARICELLE" },
    { "nom": "Somatomédine C (IGF-1)" },
    { "nom": "sous classe igG" },
    { "nom": "SPERMOCULTURE" },
    { "nom": "SPERMOCULTURE MYC/CHL" },
    { "nom": "SPERMOGRAMME" },
    { "nom": "SPERMOGRAMME ET SPERMOCYTOGRAMME" },
    { "nom": "SSA/SSB" },
    { "nom": "Sérodiagnostic de Widal et Félix" },
    { "nom": "SéROLOGIE DE L'H. PYLORI IGG/IGA( AGGLUTINATION )" },
    { "nom": "Sérologie de l'Helicobacter pylori IgG" },
    { "nom": "T.P.H.A" },
    { "nom": "TAUX DE PROTIDE (LIQUIDE DE PONCTION)" },
    { "nom": "TAUX DE RETICULOCYTES" },
    { "nom": "TEMPS DE CEPHALINE KAOLIN" },
    { "nom": "TEMPS DE COAGULATION" },
    { "nom": "TEMPS DE SAIGNEMENT" },
    { "nom": "TEST ANTIGéNIQUE  SARS COVID 2" },
    { "nom": "TEST AU ROSE BENGAL" },
    { "nom": "TEST DE COOMBS DIRECT" },
    { "nom": "Test de coombs indirect RAI" },
    { "nom": "TEST DE FALCIFORMATION" },
    { "nom": "TEST DE GROSSESSE" },
    { "nom": "TEST DE MONONUCLEOSE INFECTIEUSE M.N.I" },
    { "nom": "TEST POST COETAL" },
    { "nom": "TEST RAPIDE MULTI-DROGUES (12)" },
    { "nom": "TEST RAPIDE MULTI-DROGUES (7)" },
    { "nom": "Test respiratoire Hélicobacter pylori" },
    { "nom": "TEST REVALTAT" },
    { "nom": "testosterone libre" },
    { "nom": "THYROCALCITONINE" },
    { "nom": "THYROGLOBULINE" },
    { "nom": "THYROXINE T4" },
    { "nom": "TOXOPLASMOSE IgG" },
    { "nom": "TP INR" },
    { "nom": "TPHA" },
    { "nom": "TRANSAMINASES SERIQUES ASAT/ALAT" },
    { "nom": "TRANSFERRINE" },
    { "nom": "TRIIODOTHYRONINE" },
    { "nom": "Troponine" },
    { "nom": "TYPAGE HLA B51" },
    { "nom": "U.I.B.C" },
    { "nom": "uracilémie" },
    { "nom": "URAPLASMA" },
    { "nom": "UREE SANGUINE" },
    { "nom": "UREE URINAIRE" },
    { "nom": "VITAMIBE B6" },
    { "nom": "VITAMINE B1" },
    { "nom": "vitamine C" },
    { "nom": "VITAMINE D2/D3 : 25 HYDROXY VITAMINE D" },
    { "nom": "VITAMINE E" },
    { "nom": "Vitamine K" },
    { "nom": "WALER ROSE" },
    { "nom": "ZINC" },
    { "nom": "Taux de prothrombine" },
    { "nom": "FER SERIQUE" },
    { "nom": "BILAN LIPIDIQUE" },
    { "nom": "SEROLOGIE HYDATIDOSE" },
    { "nom": "BILIRUBINE TOTALE" },
    { "nom": "MYCOPLASMA" },
    { "nom": "SEROLOGIE HIV" },
    { "nom": "Hormone de croissance (GH)" },
    { "nom": "Cortisol" },
    { "nom": "EXAMEN MYCOLOGIQUE" },
    { "nom": "C- REACTIVE PROTEINE (CRP)" },
    { "nom": "SEROLOGIE SYPHILIS" },
    { "nom": "Bilan Complet Decembre" },
    { "nom": "HbA1C (Hb glyquée)" },
    { "nom": "Vitamine K" }
];

const pdfList = [
    "(Thyroxine libre) ft4.pdf",
    "(Thyroxine libre).pdf",
    "17-Hydroxyprogesteron.pdf",
    "AC ANTI CARDIOLIPINE IgG.pdf",
    "Ac anti DNA natif.pdf",
    "AC ANTI INSULINE 2.pdf",
    "AC ANTI INSULINE.pdf",
    "AC ANTI MITOCHONDRI.pdf",
    "Ac anti peau.pdf",
    "AC ANTI-ACIDE GLUTAMIQUE DECARBOXYLASE.pdf",
    "AC ANTI-ANTIGENES ENA.pdf",
    "AC ANTI-CARDIOLIPINE IGM.pdf",
    "AC ANTI-CARDIOLIPINE Screen (IgG, IgM).pdf",
    "AC ANTI-RETICULINE.pdf",
    "Ac anti-transglutaminase IgA.pdf",
    "Ac anti-transglutaminase IgG.pdf",
    "AC-ANTI ACETYLCHOLINE.pdf",
    "acide_lactique.pdf",
    "Aldolase.pdf",
    "ALDOSTERONE URINAIRE.pdf",
    "ALDOSTERONE.pdf",
    "alpha-foetoproteine.pdf",
    "alpha_1_anti_trypsine.pdf",
    "Amylase.pdf",
    "Anti corps anti beta.pdf",
    "anti lupique circulant.pdf",
    "Anti muscle lisse.pdf",
    "ANTI-GAD.pdf",
    "ANti-TPO.pdf",
    "ANTICORPS ANTI -THYROGLOBILINE (anti TG).pdf",
    "Anticorps anti-cytoplasme des polynucléaires neutro philes.pdf",
    "Anticorps anti-endomysium IgA.pdf",
    "Anticorps anti-muscles lisses.pdf",
    "Anticorps anti-saccharomyces cervisiae (ASCA).pdf",
    "antigéne carcino-embryonnaire.pdf",
    "ANTISTREPTOLYSINE.pdf",
    "ANTITHROMBINE 3.pdf",
    "AUTO-ANTICORPS ANTI-IA2.pdf",
    "b1bff4c8-93b7-4eef-b1d9-1189c9e87210.pdf",
    "BETA HCG.pdf",
    "c reactive.pdf",
    "CERULEOPLASMINE.pdf",
    "chain legere lambda.pdf",
    "chaine legere urinaire.pdf",
    "Chaines légéres Kappa.pdf",
    "CHLAMYDIA IgG.pdf",
    "CHLAMYDIA IgM.pdf",
    "chlamydia oga.pdf",
    "CHLAMYDIA.pdf",
    "CHOLESTEROL HDL.pdf",
    "CHOLESTEROL LDL.pdf",
    "CHROMATOGRAPHI DES ACIDE AMINES.pdf",
    "Cortisol - Copy.pdf",
    "Cortisol.pdf",
    "CPK.pdf",
    "Créatine Phosphokinase.pdf",
    "D-DIMERES.pdf",
    "depakine.pdf",
    "Déhydroépiandrostérone-sulfate.pdf",
    "Déhydroépiandrostérone.pdf",
    "ELECTROPHORESE DES PROTEINES.pdf",
    "ELECTROPHORéSE DES PROTEINES URINAIRES.pdf",
    "Enzyme de conversion de l'angiotensine.pdf",
    "facteur de willebrand.pdf",
    "facteur ix.pdf",
    "facteur ruhmatdois.pdf",
    "facteur vii.pdf",
    "FER SERIQUE.pdf",
    "FIBRINOGENE.pdf",
    "FRUCTOSAMINE.pdf",
    "Fsh.pdf",
    "Ft3.pdf",
    "GLUCOSE-6-PHOSPHATE DESHYDROGENASE (G6-PDH).pdf",
    "GLUCOSE.pdf",
    "HbA1C (Hb glyquée).pdf",
    "HbA1C (Hb glyquée)HbA1C (Hb glyquée).pdf",
    "HbA1C.pdf",
    "HCG, MARQUEUR TUMORAL.pdf",
    "HEMOSTASE (1).pdf",
    "HEMOSTASE.pdf",
    "HOMOCYSTEINE URINAIRE.pdf",
    "HOMOCYSTEINEpdf.pdf",
    "Hormone ANTI mullurienne.pdf",
    "HORMONE ANTI-DIURETIQUE.pdf",
    "Hormone de croissance (GH).pdf",
    "Hormone de croissance GH.pdf",
    "IgA anti-transglutaminase tissulaire.pdf",
    "IGE LAIT DE VACHE.pdf",
    "IGG 4.pdf",
    "IgG anti-transglutaminase.pdf",
    "Igg.pdf",
    "insuline.pdf",
    "LDH.pdf",
    "LH.pdf",
    "Lipase.pdf",
    "LKM1.pdf",
    "Locus B (Guide_immunogénétique_2018.)pdf.pdf",
    "MAGNESIUM.pdf",
    "magnisiuem.pdf",
    "Mycloplasme sur sperm.pdf",
    "OESTRADIOL.pdf",
    "peptide c.pdf",
    "PHOSPHORE.pdf",
    "phsphatase aclcaline.pdf",
    "Phénylalanine.pdf",
    "PROCALCITONINE.pdf",
    "Progesterone.pdf",
    "PROTEINE C ACTIVE.pdf",
    "PSA LIBRE.pdf",
    "PSA TOTALE.pdf",
    "PTH.pdf",
    "Somatomédine C IGF.pdf",
    "sou IGC.pdf",
    "testosterone libre.pdf",
    "Testosterone.pdf",
    "thrypoglobuline.pdf",
    "THYROCALCITONINE.pdf",
    "thyroxine t4.pdf",
    "TRANSFERRINE.pdf",
    "Tri-iodothyronine libre.pdf",
    "triiodothyronine.pdf",
    "Troponine.pdf",
    "Tshus.pdf",
    "VITAMINE D2D3  25 HYDROXY VITAMINE D.pdf",
    "ZINC.pdf"
];

const normalize = (str) => str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, '');

const mapping = {};
const finalUnmatched = [...pdfList];

// 1. First pass: Exact matches
analyses.forEach(analysis => {
    const analysisName = analysis.nom;
    const normName = normalize(analysisName);

    const match = pdfList.find(pdf => normalize(pdf.replace('.pdf', '')) === normName);
    if (match) {
        mapping[analysisName] = match;
        const index = finalUnmatched.indexOf(match);
        if (index > -1) finalUnmatched.splice(index, 1);
    }
});

// 2. Second pass: Smart partial matches for remaining analyses
analyses.forEach(analysis => {
    if (mapping[analysis.nom]) return;

    const normName = normalize(analysis.nom);
    const match = finalUnmatched.find(pdf => {
        const normPdf = normalize(pdf.replace('.pdf', ''));
        if (normPdf.length < 4) return false;
        return normName.includes(normPdf) || normPdf.includes(normName);
    });

    if (match) {
        mapping[analysis.nom] = match;
        const index = finalUnmatched.indexOf(match);
        if (index > -1) finalUnmatched.splice(index, 1);
    }
});

console.log(JSON.stringify(mapping, null, 2));
console.log("\nUNMATCHED:");
console.log(finalUnmatched);
